#!/usr/bin/env python3
"""
Script to create PRs for missing translations.
Reads the localization check results and creates a PR per locale with missing strings.
"""

import json
import sys
from pathlib import Path
import subprocess
import xml.etree.ElementTree as ET
from typing import Dict


def run_command(cmd: list, capture_output=True) -> subprocess.CompletedProcess:
    """Run a command and return the result."""
    result = subprocess.run(cmd, capture_output=capture_output, text=True)
    if result.returncode != 0:
        print(f"❌ Command failed: {' '.join(cmd)}")
        if result.stderr:
            print(f"   Error: {result.stderr}")
        sys.exit(1)
    return result


def add_missing_strings_to_xml(xml_path: Path, missing_strings: Dict[str, str]):
    """Add missing strings to an existing XML file."""
    tree = ET.parse(xml_path)
    root = tree.getroot()
    
    # Get existing string names
    existing = {elem.get('name') for elem in root.findall('string')}
    
    # Add missing strings
    for name, value in missing_strings.items():
        if name not in existing:
            string_elem = ET.SubElement(root, 'string')
            string_elem.set('name', name)
            string_elem.text = value
    
    # Write back with proper formatting
    ET.indent(tree, space='    ')
    tree.write(xml_path, encoding='utf-8', xml_declaration=True)


def create_pr_for_locale(locale: str, missing_data: Dict):
    """Create a PR for a specific locale with missing strings."""
    missing_count = missing_data['missing_count']
    missing_strings = missing_data['missing_strings']
    
    if missing_count == 0:
        print(f"✅ No missing strings for {locale.upper()}, skipping PR")
        return
    
    print(f"\n📝 Creating PR for {locale.upper()} ({missing_count} missing strings)...")
    
    # Create branch name
    branch_name = f"localization/{locale}/missing-strings"
    
    # Configure git
    run_command(['git', 'config', 'user.name', 'github-actions[bot]'])
    run_command(['git', 'config', 'user.email', 'github-actions[bot]@users.noreply.github.com'])
    
    # Check if branch already exists and delete it
    result = subprocess.run(['git', 'rev-parse', '--verify', branch_name], 
                          capture_output=True, text=True)
    if result.returncode == 0:
        print(f"   Branch {branch_name} exists, deleting...")
        run_command(['git', 'branch', '-D', branch_name])
    
    # Create and checkout new branch
    run_command(['git', 'checkout', '-b', branch_name])
    
    # Path to locale strings.xml
    locale_xml = Path(f"app/src/main/res/values-{locale}/strings.xml")
    
    # Add missing strings to the XML file
    add_missing_strings_to_xml(locale_xml, missing_strings)
    
    # Stage changes
    run_command(['git', 'add', str(locale_xml)])
    
    # Commit
    commit_msg = f"Add missing {locale.upper()} translations ({missing_count} strings)"
    run_command(['git', 'commit', '-m', commit_msg])
    
    # Push branch
    run_command(['git', 'push', '-f', 'origin', branch_name])
    
    # Create PR body
    pr_body = f"""## Missing {locale.upper()} Translations

This PR adds **{missing_count} missing translation strings** to the {locale.upper()} locale.

### Missing Strings
"""
    
    for name in list(missing_strings.keys())[:10]:
        pr_body += f"- `{name}`\n"
    
    if missing_count > 10:
        pr_body += f"\n... and {missing_count - 10} more\n"
    
    pr_body += """
### ⚠️ Action Required
The strings have been added with their **English values as placeholders**. Please:
1. Review each string
2. Translate them to proper {locale_name}
3. Ensure informal address ("tu"/"du"/"tú") is used as per project guidelines

---
*This PR was automatically generated by the localization check workflow.*
""".format(locale_name={'de': 'German', 'es': 'Spanish', 'fr': 'French', 'it': 'Italian'}[locale])
    
    # Create PR using GitHub CLI
    pr_title = f"[i18n] Add missing {locale.upper()} translations"
    
    try:
        result = run_command([
            'gh', 'pr', 'create',
            '--title', pr_title,
            '--body', pr_body,
            '--base', 'main',
            '--head', branch_name
        ])
        print(f"   ✅ PR created successfully!")
    except:
        print(f"   ℹ️  PR might already exist or gh CLI not available")
    
    # Checkout main again
    run_command(['git', 'checkout', 'main'])


def main():
    results_file = Path("localization_check_results.json")
    
    if not results_file.exists():
        print("❌ Results file not found. Run check_localizations.py first.")
        sys.exit(1)
    
    with open(results_file, 'r', encoding='utf-8') as f:
        results = json.load(f)
    
    print("🚀 Creating PRs for locales with missing strings...\n")
    
    for locale, data in results.items():
        create_pr_for_locale(locale, data)
    
    print("\n✅ Done!")


if __name__ == "__main__":
    main()
